CREATE TABLE IF NOT EXISTS `td_message` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '姓名',
	`phone` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '手机号',
	`content` VARCHAR(200) NOT NULL DEFAULT '0' COMMENT '留言内容',
	`create_time` INT(10) NOT NULL DEFAULT '0',
	`update_time` INT(10) NOT NULL DEFAULT '0',
	`touid` INT(10) NOT NULL DEFAULT '0' COMMENT '留言对象',
	PRIMARY KEY (`id`)
)
COMMENT='留言表'
ENGINE=MyISAM
